Manually configure miniconda on Travis and use pytest-xvfb
Our travis build started failing with errors like this for pyqt 4 and 5:

UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqt
  - pyqt=4.*

This commit installs miniconda manually so we can have better control at
what is going on, and install pytest-xvfb to handle xvfb for us.