Stop importing from py
py._code has been moved to _pytest._code with pytest 2.9.0:
https://docs.pytest.org/en/latest/changelog.html#id395

We still imported from py._code without actually depending from py.
While this happened to work, it now breaks due to pytest dropping py:
https://github.com/pytest-dev/pytest/pull/10396

Resulting in:

    File ".../src/pytestqt/logging.py", line 5, in <module>
        from py._code.code import TerminalRepr, ReprFileLocation
    ModuleNotFoundError: No module named 'py._code'; 'py' is not a package

with the latest pytest main.